before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - GO111MODULE=on
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  ldflags:
     - -X main.version={{.Version}}
     - -X main.revision={{.ShortCommit}}
  main: ./cmd/psutilsql/main.go
archive:
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
