name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run tests
      run: make test
